### ISSUE TITLE
Getting duplicate messages

### ISSUE THREAD

**Issue by gorangajic** [stojanovic/space-explorer-bot#2]
<img src="https://cloud.githubusercontent.com/assets/249310/16335063/e65dbeae-3a04-11e6-91cb-e29e09716686.png" width="200px"><img src="https://cloud.githubusercontent.com/assets/249310/16335066/ed50b504-3a04-11e6-8563-7aed4fbecd83.png" width="200px">

**Comment by stojanovic** [comment]
Messenger issue fixed in the meantime.
