### ISSUE TITLE
`Curiosity` and `Show` don't seem to be working

### ISSUE THREAD

**Issue by html5cat** [stojanovic/space-explorer-bot#4]
If it helps, in the logs there are a few:
`{
    "errorMessage": "X-Hub-Signatures does not match"
}`
I was also not asked for `nasaApiKey` or `dbName` during setup – are they set automatically?

**Comment by stojanovic** [comment]
We just published a new version of Claudia bot builder and it asks for that X-Hub-Signature, but that should be just a warning.

I'll look into it, in the meantime, can you please try to add `nasaApiKey` manually in API Gateway stage variables and try again? Don't worry about DB name, it's not used at the moment, I'll move it to a branch.

**Comment by html5cat** [comment]
Added manually, works like a charm!

**Comment by stojanovic** [comment]
Will fix it soon, thanks for reporting :)

**Comment by stojanovic** [comment]
Ah, it's not the issue with the code, it's an issue with the documentation :(
You need to run `claudia` command with `--configure-app` flag to ask those questions.
I'll update it.
Thanks again.
