### ISSUE TITLE
Nothing comes up via the flow menu approach, api.ai token?

### ISSUE THREAD

**Issue by MunlyLeong** [stojanovic/space-explorer-bot#6]
Hi,

I can make a "single page" bot just fine (everything in bot.js) but when I try to deploy this example, even as-is. Nothing comes up. I suspect it's the missing api.ai key. I've got the NASA key in there but do we literally need to train an API.ai agent with all these plain text responses i.e. MAIN_MENU just to get this approach to work? 

I"m about to do that now in a sec

**Comment by stojanovic** [comment]
I need to update the documentation.
No need to do a full training, it is trained just for ISS now, I'll attach the screenshot.
Try deploying with `--configure-bot` flag, so `claudia update --configure-bot` or of course create.

**Comment by stojanovic** [comment]
It will work even without this as long as you set the API key:
<img width="661" alt="screen shot 2017-02-10 at 13 04 10" src="https://cloud.githubusercontent.com/assets/613478/22826203/78e430c2-ef91-11e6-9f96-4b80c47aed0c.png">
<img width="659" alt="screen shot 2017-02-10 at 13 04 02" src="https://cloud.githubusercontent.com/assets/613478/22826202/78e22034-ef91-11e6-93fc-43ad26d15dc1.png">

**Comment by MunlyLeong** [comment]
ok so I was right but what about making it work without Api.ai at all? this is an annoyance. I know you want to demonstrate that you can plug an NLP into it so far.

Btw i think my issue might even be unrelated to api.ai. Probably amazon lambda not being able to find the paths of flows. Same issue with the graphic assets. I had to hardlink them elsewhere vs doing "./flow/" etc to get them to show

**Comment by stojanovic** [comment]
This and older versions don't need API.ai: https://github.com/stojanovic/space-explorer-bot/tree/b997de1fcb1572e0acb1e575d51724a8a8d98898

Try it and let me know if you still have an issue.
